.DEFAULT_GOAL := build-run

run-dist:
	./build/install/app/bin/app

clean:
	./gradlew clean

build:
	./gradlew clean build

run:
	./gradlew run

install:
	./gradlew clean installDist

test:
	./gradlew test


build-run: build run

.PHONY: build






